version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker
    restart: unless-stopped
    ports:
      - "5672:5672"   
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - laravel-rabbitmq-async-workers

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-rabbitmq-async-workers-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - rabbitmq
    networks:
      - laravel-rabbitmq-async-workers

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-rabbitmq-queue-worker
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "php artisan rabbitmq:queue-declare default && supervisord -n -c /etc/supervisor/supervisord.conf"
    depends_on:
      - rabbitmq
      - app
    networks:
      - laravel-rabbitmq-async-workers

networks:
  laravel-rabbitmq-async-workers:
    driver: bridge

volumes:
  rabbitmq_data: