[program:laravel-worker-pix]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=payment.pix --sleep=1 --timeout=30 --memory=256 --tries=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker-pix-%(process_num)02d.log
stopwaitsecs=60

[program:laravel-worker-boleto]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=payment.boleto --sleep=3 --timeout=120 --memory=256 --tries=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker-boleto-%(process_num)02d.log
stopwaitsecs=120

[program:laravel-worker-credit-card]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=payment.credit_card --sleep=2 --timeout=60 --memory=256 --tries=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker-credit-card-%(process_num)02d.log
stopwaitsecs=60